apiVersion: v1
kind: Service
metadata:
  name: breast-cancer-service
spec:
  type: NodePort
  selector:
    app: breast-cancer
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30007