name: CI/CD Modelo Breast Cancer

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  tests:
    name: Pruebas rápidas de endpoints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Instalar dependencias
        run: pip install -r requirements.txt
      - name: Lanzar API en background
        run: |
          python api.py &
          echo $! > api.pid
          sleep 5
      - name: Probar /
        run: |
          curl -sSf http://127.0.0.1:5000/ | tee get.json
          grep '"status"' get.json
      - name: Probar /predict
        run: |
          curl -sSf -X POST http://127.0.0.1:5000/predict \
            -H 'Content-Type: application/json' \
            -d '{"features": [17.990000,10.380000,122.800000,1001.000000,0.118400,0.277600,0.300100,0.147100,0.241900,0.078710,1.095000,0.905300,8.589000,153.400000,0.006399,0.049040,0.053730,0.015870,0.030030,0.006193,25.380000,17.330000,184.600000,2019.000000,0.162200,0.665600,0.711900,0.265400,0.460100,0.118900]}' | tee predict.json
          grep '"prediction"' predict.json
      - name: Apagar API
        if: always()
        run: |
          kill $(cat api.pid) || true

  build-and-push:
    name: Construir y publicar imagen
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Construir y subir
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/breast-cancer-ml-api:latest,${{ secrets.DOCKERHUB_USERNAME }}/breast-cancer-ml-api:${{ github.sha }}
      - name: Mostrar digest
        run: |
          echo "Digest: ${{ steps.build.outputs.digest }}" || echo "Digest no disponible"